"""
Alerts Page
Displays security alerts generated by the rule engine.
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QFrame,
    QPushButton, QTableWidget, QTableWidgetItem, QHeaderView,
    QGroupBox, QMessageBox, QSplitter, QTextEdit
)
from PyQt6.QtCore import Qt, pyqtSignal
from PyQt6.QtGui import QColor

from .widgets import AlertsList, SearchBar


class AlertsPage(QWidget):
    """
    Page for viewing and managing security alerts.
    """

    acknowledge_requested = pyqtSignal(str)
    block_ip_requested = pyqtSignal(str)
    clear_alerts_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._alerts = []
        self.setup_ui()

    def setup_ui(self):
        """Setup the alerts page UI."""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(20)

        # Header
        header_layout = QHBoxLayout()

        title = QLabel("Security Alerts")
        title.setProperty("class", "title")
        header_layout.addWidget(title)

        header_layout.addStretch()

        # Alert count
        self.alert_count_label = QLabel("Total: 0 | Unacknowledged: 0")
        header_layout.addWidget(self.alert_count_label)

        # Clear button
        clear_btn = QPushButton("Clear All")
        clear_btn.setProperty("class", "danger")
        clear_btn.clicked.connect(self._on_clear_all)
        header_layout.addWidget(clear_btn)

        layout.addLayout(header_layout)

        # Filters
        filter_layout = QHBoxLayout()

        self.search_bar = SearchBar(
            placeholder="Search alerts...",
            filters=["All", "Critical", "High", "Medium", "Low", "Unacknowledged"]
        )
        self.search_bar.search_changed.connect(self._filter_alerts)
        self.search_bar.filter_changed.connect(self._filter_alerts)
        filter_layout.addWidget(self.search_bar, 1)

        layout.addLayout(filter_layout)

        # Main content splitter
        splitter = QSplitter(Qt.Orientation.Vertical)

        # Alerts table
        self.alerts_table = QTableWidget()
        self.alerts_table.setColumnCount(7)
        self.alerts_table.setHorizontalHeaderLabels([
            "Time", "Severity", "Rule", "Title", "Process", "IP", "Actions"
        ])

        header = self.alerts_table.horizontalHeader()
        header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        header.setStretchLastSection(True)

        self.alerts_table.setColumnWidth(0, 150)
        self.alerts_table.setColumnWidth(1, 80)
        self.alerts_table.setColumnWidth(2, 120)
        self.alerts_table.setColumnWidth(3, 250)
        self.alerts_table.setColumnWidth(4, 100)
        self.alerts_table.setColumnWidth(5, 120)

        self.alerts_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.alerts_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
        self.alerts_table.cellClicked.connect(self._on_alert_selected)

        splitter.addWidget(self.alerts_table)

        # Alert details panel
        details_widget = QWidget()
        details_layout = QVBoxLayout(details_widget)
        details_layout.setContentsMargins(0, 10, 0, 0)

        details_label = QLabel("Alert Details")
        details_label.setStyleSheet("font-weight: bold; font-size: 12pt;")
        details_layout.addWidget(details_label)

        self.details_text = QTextEdit()
        self.details_text.setReadOnly(True)
        self.details_text.setMaximumHeight(200)
        self.details_text.setPlaceholderText("Select an alert to view details...")
        details_layout.addWidget(self.details_text)

        # Recommended action
        action_layout = QHBoxLayout()
        self.recommended_action_label = QLabel("Recommended Action: -")
        self.recommended_action_label.setWordWrap(True)
        action_layout.addWidget(self.recommended_action_label, 1)

        self.take_action_btn = QPushButton("Take Recommended Action")
        self.take_action_btn.setProperty("class", "primary")
        self.take_action_btn.setEnabled(False)
        self.take_action_btn.clicked.connect(self._on_take_action)
        action_layout.addWidget(self.take_action_btn)

        details_layout.addLayout(action_layout)

        splitter.addWidget(details_widget)

        splitter.setSizes([400, 200])
        layout.addWidget(splitter, 1)

        # Stats at bottom
        self._setup_stats_section(layout)

    def _setup_stats_section(self, parent_layout):
        """Setup the statistics section."""
        stats_group = QGroupBox("Alert Statistics")
        stats_layout = QHBoxLayout(stats_group)

        # Severity breakdown
        self.critical_count = QLabel("Critical: 0")
        self.critical_count.setStyleSheet("color: #9C27B0; font-weight: bold;")
        stats_layout.addWidget(self.critical_count)

        self.high_count = QLabel("High: 0")
        self.high_count.setStyleSheet("color: #f44336; font-weight: bold;")
        stats_layout.addWidget(self.high_count)

        self.medium_count = QLabel("Medium: 0")
        self.medium_count.setStyleSheet("color: #FF9800; font-weight: bold;")
        stats_layout.addWidget(self.medium_count)

        self.low_count = QLabel("Low: 0")
        self.low_count.setStyleSheet("color: #4CAF50; font-weight: bold;")
        stats_layout.addWidget(self.low_count)

        stats_layout.addStretch()

        parent_layout.addWidget(stats_group)

    def add_alert(self, alert):
        """Add a new alert to the display."""
        self._alerts.insert(0, alert)
        self._refresh_table()
        self._update_stats()

    def update_alerts(self, alerts: list):
        """Update the entire alerts list."""
        self._alerts = alerts
        self._refresh_table()
        self._update_stats()

    def _refresh_table(self):
        """Refresh the alerts table."""
        # Apply filters first
        search_text = self.search_bar.get_text().lower()
        filter_type = "All"
        if hasattr(self.search_bar, 'filter_combo'):
            filter_type = self.search_bar.filter_combo.currentText()

        filtered = []
        for alert in self._alerts:
            # Apply severity filter
            if filter_type == "Critical" and alert.severity.value != "critical":
                continue
            if filter_type == "High" and alert.severity.value != "high":
                continue
            if filter_type == "Medium" and alert.severity.value != "medium":
                continue
            if filter_type == "Low" and alert.severity.value != "low":
                continue
            if filter_type == "Unacknowledged" and alert.is_acknowledged:
                continue

            # Apply search filter
            if search_text:
                searchable = f"{alert.title} {alert.description} {alert.process_name} {alert.source_ip} {alert.dest_ip}".lower()
                if search_text not in searchable:
                    continue

            filtered.append(alert)

        # Update table
        self.alerts_table.setRowCount(len(filtered))

        for row, alert in enumerate(filtered):
            # Time
            time_str = alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')
            self.alerts_table.setItem(row, 0, QTableWidgetItem(time_str))

            # Severity
            severity_item = QTableWidgetItem(alert.severity.value.upper())
            severity_colors = {
                'low': '#4CAF50', 'medium': '#FF9800',
                'high': '#f44336', 'critical': '#9C27B0'
            }
            severity_item.setForeground(QColor(severity_colors.get(alert.severity.value, '#888')))
            self.alerts_table.setItem(row, 1, severity_item)

            # Rule
            self.alerts_table.setItem(row, 2, QTableWidgetItem(alert.rule_name))

            # Title
            title_item = QTableWidgetItem(alert.title)
            if alert.is_acknowledged:
                title_item.setForeground(QColor('#888'))
            self.alerts_table.setItem(row, 3, title_item)

            # Process
            self.alerts_table.setItem(row, 4, QTableWidgetItem(alert.process_name or "-"))

            # IP
            ip = alert.source_ip or alert.dest_ip or "-"
            self.alerts_table.setItem(row, 5, QTableWidgetItem(ip))

            # Actions
            action_widget = QWidget()
            action_layout = QHBoxLayout(action_widget)
            action_layout.setContentsMargins(4, 2, 4, 2)
            action_layout.setSpacing(4)

            if not alert.is_acknowledged:
                ack_btn = QPushButton("Ack")
                ack_btn.setFixedSize(50, 24)
                ack_btn.clicked.connect(lambda checked, a=alert: self._acknowledge_alert(a.id))
                action_layout.addWidget(ack_btn)

            target_ip = alert.source_ip or alert.dest_ip
            if target_ip and target_ip not in ("-", "", "127.0.0.1"):
                block_btn = QPushButton("Block")
                block_btn.setFixedSize(50, 24)
                block_btn.setStyleSheet("background-color: #f44336; color: white;")
                block_btn.clicked.connect(lambda checked, ip=target_ip: self.block_ip_requested.emit(ip))
                action_layout.addWidget(block_btn)

            action_layout.addStretch()
            self.alerts_table.setCellWidget(row, 6, action_widget)

            # Store alert reference
            self.alerts_table.item(row, 0).setData(Qt.ItemDataRole.UserRole, alert)

    def _update_stats(self):
        """Update statistics labels."""
        total = len(self._alerts)
        unack = sum(1 for a in self._alerts if not a.is_acknowledged)
        self.alert_count_label.setText(f"Total: {total} | Unacknowledged: {unack}")

        critical = sum(1 for a in self._alerts if a.severity.value == 'critical')
        high = sum(1 for a in self._alerts if a.severity.value == 'high')
        medium = sum(1 for a in self._alerts if a.severity.value == 'medium')
        low = sum(1 for a in self._alerts if a.severity.value == 'low')

        self.critical_count.setText(f"Critical: {critical}")
        self.high_count.setText(f"High: {high}")
        self.medium_count.setText(f"Medium: {medium}")
        self.low_count.setText(f"Low: {low}")

    def _filter_alerts(self):
        """Apply search and filter."""
        self._refresh_table()

    def _on_alert_selected(self, row, col):
        """Handle alert selection."""
        item = self.alerts_table.item(row, 0)
        if item:
            alert = item.data(Qt.ItemDataRole.UserRole)
            if alert:
                self._show_alert_details(alert)

    def _show_alert_details(self, alert):
        """Show alert details in the details panel."""
        self._selected_alert = alert

        details = f"""
<h3>{alert.title}</h3>
<p><b>Severity:</b> {alert.severity.value.upper()}</p>
<p><b>Rule:</b> {alert.rule_name} ({alert.rule_id})</p>
<p><b>Time:</b> {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
<p><b>Description:</b> {alert.description}</p>
"""

        if alert.process_name:
            details += f"<p><b>Process:</b> {alert.process_name} (PID: {alert.pid})</p>"

        if alert.source_ip:
            details += f"<p><b>Source:</b> {alert.source_ip}:{alert.source_port}</p>"

        if alert.dest_ip:
            details += f"<p><b>Destination:</b> {alert.dest_ip}:{alert.dest_port}</p>"

        if alert.metadata:
            details += "<p><b>Additional Info:</b></p><ul>"
            for key, value in alert.metadata.items():
                details += f"<li>{key}: {value}</li>"
            details += "</ul>"

        self.details_text.setHtml(details)

        # Update recommended action
        if alert.recommended_action:
            self.recommended_action_label.setText(f"Recommended Action: {alert.recommended_action}")
            self.take_action_btn.setEnabled(True)
        else:
            self.recommended_action_label.setText("Recommended Action: -")
            self.take_action_btn.setEnabled(False)

    def _acknowledge_alert(self, alert_id: str):
        """Acknowledge an alert."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.is_acknowledged = True
                break
        self._refresh_table()
        self._update_stats()
        self.acknowledge_requested.emit(alert_id)

    def _on_take_action(self):
        """Handle take recommended action button."""
        if hasattr(self, '_selected_alert') and self._selected_alert:
            alert = self._selected_alert
            target_ip = alert.source_ip or alert.dest_ip

            if target_ip and target_ip not in ("-", "", "127.0.0.1"):
                reply = QMessageBox.question(
                    self, "Confirm Action",
                    f"Do you want to block IP: {target_ip}?",
                    QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
                )
                if reply == QMessageBox.StandardButton.Yes:
                    self.block_ip_requested.emit(target_ip)
                    self._acknowledge_alert(alert.id)
            else:
                QMessageBox.information(
                    self, "Info",
                    "No specific IP to block for this alert. The alert has been acknowledged."
                )
                self._acknowledge_alert(alert.id)

    def _on_clear_all(self):
        """Handle clear all alerts."""
        reply = QMessageBox.question(
            self, "Confirm Clear",
            "Are you sure you want to clear all alerts?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )
        if reply == QMessageBox.StandardButton.Yes:
            self._alerts.clear()
            self._refresh_table()
            self._update_stats()
            self.details_text.clear()
            self.clear_alerts_requested.emit()

    def get_unacknowledged_count(self) -> int:
        """Get count of unacknowledged alerts."""
        return sum(1 for a in self._alerts if not a.is_acknowledged)
